# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: youth

#on:
  #push:
    branches: 
     - master 

  #schedule:
     - cron: '20 18 * * *'
  watch:
    types: started

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: npm install
        run: |
          npm install
      - name: '运行 【中青看点】'
        run: |
          node youth.js
        env:
          signheaderVal: ${{ secrets.YOUTH_HEADER }}
          redpbodyVal: ${{ secrets.YOUTH_REDBODY }}
          articlebodyVal: ${{ secrets.YOUTH_ARTBODY }}
          timebodyVal: ${{ secrets.YOUTH_TIME }}
          PUSH_KEY: ${{ secrets.PUSH_KEY }}
          BARK_PUSH: ${{ secrets.BARK_PUSH }}
